name: sign in toudingmaohuo task

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # 设置Node.js的版本
    
    - name: Run JavaScript
      run: node script.ts